### ISSUE TITLE
Resize popup window

### ISSUE THREAD

**Issue by sdgandhi** [brechtm/GoogleKeepMenu#2]
The popup window is about 50px too narrow to fit the page without horizontal scrolling.

**Comment by brechtm** [comment]
Thanks for the report. I think Google may have changed the Keep webpage layout recently.

Not sure when I'll get to creating a new release. For future reference, I think the following lines will need changing: https://github.com/brechtm/GoogleKeepMenu/blob/8edc2b21032558fcd2174977e40235f7ca7c16a5/GoogleKeepMenu/Base.lproj/Main.storyboard#L689-L693

**Comment by sdgandhi** [comment]
Yeah, I already did it in my fork at https://github.com/NewNoetic/GoogleKeepMenu

But I'm having a problem with the archived app (running from xcode directly works). It keeps saying the content view controller is nil. As if it's not loading it from the storyboard. Have you run into that before?

**Comment by brechtm** [comment]
Please provide a pull request when you already have a fix. This saves duplicated work and thus time.

I haven't built this project in a long time and I'm not really familiar with Swift or XCode. So I don't really have a clue as to what could be wrong. It's probably due to a backward-incompatible change in XCode.

**Comment by sdgandhi** [comment]
I just couldn't get xcode to build a proper binary, so I just wrote the app from scratch again (following the same guide you did 😂)

**Comment by brechtm** [comment]
Did this by any chance help you find out why the application bundle of this project isn't working?

**Comment by brechtm** [comment]
Fixed in 0.2.0
